### ISSUE TITLE
40px top margin added to wrapped content

### ISSUE THREAD

**Issue by ckeeney** [crossfield/react-read-more#2]
Content contained in a `ReadMore` component has a 40px top margin added.  The problem is demonstrated clearly in this screenshot.

![image](https://user-images.githubusercontent.com/8799010/45712794-120ede00-bb42-11e8-9345-34a3f4969272.png)

**Comment by ckeeney** [comment]
The offending code is at https://github.com/crossfield/react-read-more/blob/86932b81de8d2147c141c827f55e1c07cf603381/src/index.js#L43-L52

Is there a reason for this?  If not, I'm happy to open a pull request removing this top margin.

**Comment by zackify** [comment]
No, there isn't. Sorry about that :) just pushed a release! https://github.com/crossfield/react-read-more/releases/tag/0.1.0

**Comment by ckeeney** [comment]
5 minutes between issue report and release?  that's unreal.

**Comment by zackify** [comment]
Haha, I saw there was an open PR that i forgot about when you made this issue, i felt bad ;P

**Comment by ckeeney** [comment]
It all works now.  Amazingly fast support. Thanks again.

![image](https://user-images.githubusercontent.com/8799010/45714473-8cd9f800-bb46-11e8-98ae-74f684fce342.png)

**Comment by zackify** [comment]
I need to auto publish this on commits to master haha. no problem
